/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */

plugins {
    // Apply the Kotlin JVM plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm") version "1.3.70"

    // Apply the application plugin to add support for building a CLI application.
    application
}

repositories {
    // Use jcenter for resolving dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
    maven(url="https://jitpack.io")
}

dependencies {
    // Align versions of all Kotlin components
    implementation(platform("org.jetbrains.kotlin:kotlin-bom"))

    // Use the Kotlin JDK 8 standard library.
    implementation("org.jetbrains.kotlin:kotlin-stdlib:1.3.30")

    // This dependency is used by the application.
    implementation(group="com.google.guava", name="guava", version="28.0-jre")

    // Lava-player
    implementation(group="com.sedmelluq", name="lavaplayer", version="1.3.50")

    // Discord
    implementation(group="com.github.DV8FromTheWorld", name="JDA", version="v4.1.1")
    implementation(group="org.slf4j", name="slf4j-simple", version="1.7.25")

    // Jackson
    implementation(group="com.fasterxml.jackson.core", name="jackson-databind", version="2.10.0")
    implementation(group="com.fasterxml.jackson.module", name="jackson-module-kotlin", version="2.9.0")

    // Youtube API
    implementation(group="com.google.apis", name="google-api-services-youtube", version="v3-rev221-1.25.0")
}

tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile> {
    kotlinOptions.jvmTarget = "11"
}

tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
}

run {
    val run: JavaExec by tasks
    run.standardInput = System.`in`
}

application {
    // Define the main class for the application.
    mainClassName = "kotte.AppKt"
}
